--- !ditz.rubyforge.org,2008-03-06/project 
name: shoes
version: "0.1"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: shoes
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: Curious
  status: :released
  release_time: 2008-01-08 15:00:00 Z
  log_events: 
  - - 2008-04-02 15:15:31.384943 Z
    - _why <why@whytheluckystiff.net>
    - created
    - The first version of Shoes. Right before r400.
  - - 2008-04-02 15:18:48.506461 Z
    - _why <why@whytheluckystiff.net>
    - released
    - The first release of Shoes.
- !ditz.rubyforge.org,2008-03-06/release 
  name: Raisins
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-04-02 15:17:12.803117 Z
    - _why <why@whytheluckystiff.net>
    - created
    - |-
      * Multiple window support
      * Error / logging console
      * OS X improvements
      * Shape events and shape positioning
- !ditz.rubyforge.org,2008-03-06/release 
  name: Murder
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-04-02 15:17:45.417106 Z
    - _why <why@whytheluckystiff.net>
    - created
    - |-
      * Basic menuing
      * An `audio` object
      * The `image` block syntax
- !ditz.rubyforge.org,2008-03-06/release 
  name: Feinstein
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-04-02 15:18:08.652997 Z
    - _why <why@whytheluckystiff.net>
    - created
    - |-
      * Shy installer / builder.
      * Completion of the manual.
